"""Data-quality and exploratory checks -> reports/data_quality.md.  Run: python src/eda.py"""
import pandas as pd

import config as C
from db import query

REPORT = C.ROOT / "reports" / "data_quality.md"


def table(df):
    cols = list(df.columns)
    rows = ["| " + " | ".join(map(str, r)) + " |" for r in df.astype(str).itertuples(index=False)]
    return "\n".join(["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols), *rows])


def main():
    out = ["# Data quality & EDA report", f"_Window {C.START_DATE} to {C.END_DATE}. Generated by `src/eda.py`._", ""]
    sizes, nulls, dupes = [], [], []
    for n in ("depots", "drivers", "vehicles", "trips", "maintenance", "sensor_readings"):
        df = query(f"SELECT * FROM {n}")
        sizes.append((n, len(df), df.shape[1]))
        nulls.append((n, int(df.isna().sum().sum())))
        dupes.append((n, int(df.drop(columns="id").duplicated().sum())))
    out += ["## Tables", table(pd.DataFrame(sizes, columns=["table", "rows", "columns"])), "",
            "Missing values per table: " + ", ".join(f"{n}={k}" for n, k in nulls),
            "", "Fully duplicated rows (ignoring id): " + ", ".join(f"{n}={k}" for n, k in dupes), ""]

    t = query("SELECT t.*, v.fuel_type, v.vehicle_type FROM trips t JOIN vehicles v ON v.id = t.vehicle_id")
    t["kmpl"] = t.distance_km / t.fuel_litres
    out += ["## Trips", table(t[["distance_km", "fuel_litres", "kmpl", "fuel_cost_pkr", "harsh_braking_events"]].describe().round(2).reset_index()), ""]
    by = t.groupby("vehicle_type").agg(trips=("id", "count"), km_per_l=("kmpl", "median"), harsh=("harsh_braking_events", "mean")).round(2).reset_index()
    out += ["Efficiency by vehicle type (median km/l):", table(by), ""]
    q = t.groupby(t.trip_date.str[:4]).agg(trips=("id", "count"), km=("distance_km", "sum"), cost_pkr=("fuel_cost_pkr", "sum")).reset_index()
    out += ["Yearly totals:", table(q), ""]

    m = query("SELECT * FROM maintenance")
    g = m.groupby("kind").agg(jobs=("id", "count"), total_cost=("cost_pkr", "sum"), avg_cost=("cost_pkr", "mean"), downtime_days=("downtime_days", "sum")).round(0).reset_index()
    out += ["## Maintenance", table(g), ""]
    bd = m[m.kind == "Breakdown"].groupby("vehicle_id").size()
    out += [f"Breakdowns per vehicle: min {bd.min()}, median {bd.median():.0f}, max {bd.max()} "
            f"({len(bd)} of 58 vehicles had at least one).", ""]

    f = pd.read_csv(C.PROCESSED / "features.csv")
    out += ["## Modelling table", f"{len(f)} weekly snapshots, {f.breakdown_next_30d.mean():.1%} positive (breakdown within 30 days). "
            "Columns with missing values (no prior service recorded yet):", "",
            table(f.isna().mean().round(3)[lambda s: s > 0].rename("share_missing").reset_index().rename(columns={"index": "column"})), "",
            "## Known limitations",
            "- Fleet data is simulated; fuel-price history is a smooth drift to today's rates, not real historical prices.",
            "- Fuel anomalies were injected at +35% to +120% litres, so they are easy to separate.",
            "- Engine-sensor rows come from a public dataset whose label meaning is undocumented (label 0 assumed 'needs attention')."]
    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {REPORT}")


if __name__ == "__main__":
    main()
